# Generated by Django 5.2.6 on 2025-09-24 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
