# Generated by Django 5.2.6 on 2025-09-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
