# Generated by Django 5.2.6 on 2025-09-28 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
